name: build_number_increment
on: push
jobs:
  build_number_increment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Replace Build Number
        run: |
          VERSIONS=`find . -name 'build.gradle' | xargs sed -e "s/versions \(.*\)/\1/"`
          echo $VERSIONS