name: build_number_increment
on: push
jobs:
  build_number_increment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Replace Build Number
        run: |
          cd app
          sed s/versionCode 9/versionCode 10/ build.gradle
          sed s/versionName "1.8.0"/versionName "1.9.0"/ build.gradle
          cat build.gradle