name: build_number_increment
on:
  pull_request:
    branches:
      - actions/test-main

jobs:
  build_number_increment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Replace Build Number
        run: |
          # 取得
          VERSION_CODE=`find . -name 'build.gradle' | xargs grep -n '.*versionCode' | sed -r 's/.*versionCode (.*)$/\1/'`
          VERSION_NAME_MINOR=`find . -name 'build.gradle' | xargs grep -n '.*versionName' | sed -r 's/.*versionName .*\.(.*)\..*$/\1/'`
          # 加算し置換後の文字列を生成
          VERSION_CODE=$(($VERSION_CODE+1))
          VERSION_NAME_MINOR=$(($VERSION_NAME_MINOR+1))
          NEW_VERSION_CODE="versionCode $VERSION_CODE"
          NEW_VERSION_NAME_MINOR="1.$VERSION_NAME_MINOR.0"
          # 置換
          find . -name 'build.gradle' | xargs sed -ie "s/versionCode.*/versionCode $NEW_VERSION_CODE/g"
          find . -name 'build.gradle' | xargs sed -ie "s/versionName.*/versionName $NEW_VERSION_NAME_MINOR/g"
          find . -name 'build.gradle' | xargs grep 'versionCode.*'
          find . -name 'build.gradle' | xargs grep 'versionName.*'
          git branch
          # commit/push
          git config --global user.email "maccho.chekera@gmail.com"
          git config --global user.name "Chekera0127!"
          git add .
          git commit -m 'increment version code'
          git push